In [2]:
#!/usr/bin/python
import numpy as np
import pandas as pd
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import os
import glob
import sys
import imp

In [3]:
directory = '/raid/togzhan_syrymova/lump_project/data/'
os.chdir(directory)
listdir_all = glob.glob('all*raw*')
listdir_test = glob.glob('test*raw*')
print(listdir_all)
print(listdir_test)
all_subject_pressure_data_without_raw = pd.read_csv(listdir_all[0], sep = ',', header = None)
all_subject_pressure_data_with_raw = pd.read_csv(listdir_all[1], sep = ',', header = None)
test_pressure_data_without_raw = pd.read_csv(listdir_test[0], sep = ',', header = None)
test_pressure_data_with_raw = pd.read_csv(listdir_test[1], sep = ',', header = None)

['all_subject_pressure_data_without_raw.csv', 'all_subject_pressure_data_with_raw.csv']
['test_pressure_data_without_raw.csv', 'test_pressure_data_with_raw.csv']

In [7]:
################################################################
# ONLY TO SAVE ALL DATA TOGETHER
directory = '/raid/togzhan_syrymova/lump_project/data/'
all_data_with_raw = pd.concat([ \
                     pd.DataFrame(all_subject_pressure_data_with_raw.values[:]), \
                     pd.DataFrame(test_pressure_data_with_raw.values[:]) 
                               ], axis = 1)
all_data_without_raw = pd.concat([ \
                     pd.DataFrame(all_subject_pressure_data_without_raw.values[:]), \
                     pd.DataFrame(test_pressure_data_without_raw.values[:]) 
                               ], axis = 1)
all_data_with_raw.to_csv(directory + 'all_data_with_raw.csv', index=False, header = False)
all_data_without_raw.to_csv(directory +'all_data_without_raw.csv', index=False, header = False)
################################################################

In [32]:
range_1 = 6
range_2 = 7
train_dev_without = pd.concat([ \
                     pd.DataFrame(all_subject_pressure_data_without_raw.values[:, 0 : range_1*32]), \
                     pd.DataFrame(test_pressure_data_without_raw.values[:]) 
                               ], axis = 1)
train_dev_with = pd.concat([ \
                     pd.DataFrame(all_subject_pressure_data_with_raw.values[:, 0 : range_1*32]), \
                     pd.DataFrame(test_pressure_data_with_raw.values[:]) 
                               ], axis = 1)

test_without = pd.DataFrame(all_subject_pressure_data_without_raw.values[:, range_2*32:])
test_with = pd.concat(pd.DataFrame(all_subject_pressure_data_with_raw.values[:, range_2*32:]))

# TEST

In [67]:
test_subject_1 = 6
test_subject_2 = 7
directory = '/raid/togzhan_syrymova/lump_project/data/'
os.chdir(directory)
listdir_all = glob.glob('all*raw*')
listdir_test = glob.glob('test*raw*')
print(listdir_all)
print(listdir_test)
all_data_with_raw = pd.read_csv("all_subject_pressure_data_without_raw.csv", sep = ',', header = None)
all_data_without_raw = pd.read_csv("all_subject_pressure_data_with_raw.csv", sep = ',', header = None)
data = 32*9
train_dev_without = pd.concat([ \
         pd.DataFrame(all_data_without_raw.values[:, 0:test_subject_1*data]), \
         pd.DataFrame(all_data_without_raw.values[:, test_subject_1*data:(test_subject_2 - 1)*data]),
         pd.DataFrame(all_data_without_raw.values[:, (test_subject_2+1)*data:])
                              ], axis = 1)
train_dev_with = pd.concat([ \
         pd.DataFrame(all_data_with_raw.values[:, 0:test_subject_1*data]), \
         pd.DataFrame(all_data_with_raw.values[:, test_subject_1*data:(test_subject_2 - 1)*data]),
         pd.DataFrame(all_data_with_raw.values[:, (test_subject_2+1)*data:])
                           ], axis = 1)
# test sets
test_without = pd.concat([ \
         pd.DataFrame(all_data_without_raw.values[:, test_subject_1*data:(test_subject_1+1)*data]), \
         pd.DataFrame(all_data_without_raw.values[:, test_subject_2*data:(test_subject_2+1)*data]),
                           ], axis = 1)

test_with = pd.concat([ \
         pd.DataFrame(all_data_with_raw.values[:, test_subject_1*data:(test_subject_1+1)*data]), \
         pd.DataFrame(all_data_with_raw.values[:, test_subject_2*data:(test_subject_2+1)*data]),
                           ], axis = 1)
print(np.shape(train_dev_without))

['all_subject_pressure_data_without_raw.csv', 'all_data_with_raw.csv', 'all_subject_pressure_data_with_raw.csv', 'all_data_without_raw.csv']
['test_pressure_data_without_raw.csv', 'test_pressure_data_with_raw.csv']
(16800, 2304)

In [70]:
print(np.shape(df_data))
print(np.shape(train_dev_without))
print(np.shape(train_dev_with))

(16800, 4608)
(16800, 2304)
(16800, 2304)

In [128]:
# train_dev_without, train_dev_with, test_without, test_with = separate_subjects(test_subject_1, test_subject_2)
#     train_dev_without, train_dev_with, test_without, test_with = separate_subjects(test_subject_1, test_subject_2)
var = '_s_' + str(test_subject_1) + '_s_' + str(test_subject_2)
train_dev_without.columns = [''] * len(train_dev_without.columns)
train_dev_with.columns = [''] * len(train_dev_with.columns)
##### LABELS
label_with = []
label_without = []
labels_with_ = pd.DataFrame()
for i in range(np.shape(train_dev_without)[1]):
    label_with.append(1)
    label_without.append(0)
label_with = pd.DataFrame(label_with)
label_without = pd.DataFrame(label_without)
for i in range(9):
    labels_with_ = pd.concat([labels_with_, pd.DataFrame(np.zeros(32) + i)]) # 9 prot from 0 to 32

labels_with_ = pd.DataFrame(labels_with_.values[:].repeat(8))
labels_with__ = (label_with.values[:])*10 + (labels_with_.values[:]) 
bin_labels = pd.concat([pd.DataFrame(label_without), pd.DataFrame(labels_with__)], axis = 0)
##### 
# df_train, df_eval = train_test_split(df_data, test_size = 1.0/3, random_state=777, stratify = bin_labels)

# df_train.to_csv(directory + "df_train" + var + ".csv", index=False, header = False) # , header = False
# df_eval.to_csv(directory + "df_dev" + var + ".csv", index=False, header = False)
# test_with.to_csv(directory + "test_pressure_data_with" + var + ".csv", index=False, header = False)
# test_without.to_csv(directory + "test_pressure_data_without" + var + ".csv", index=False, header = False)

In [133]:
df_data = pd.concat([pd.DataFrame(train_dev_without), pd.DataFrame(train_dev_with)], axis = 1)
# df_data = pd.concat([pd.DataFrame(df_data), pd.DataFrame(bin_labels)], axis = 1)
# df_data = df_data.transpose()
# df_data = df_data.reset_index(drop=True)

In [135]:
bin_labels

         0
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
...    ...
2299  18.0
2300  18.0
2301  18.0
2302  18.0
2303  18.0

[4608 rows x 1 columns]

In [134]:
df_data

,,,,,,,,,,,...,,,,,,,,,,
0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,...,1.0,1.0,1.0,1.0,5.0,1.0,1.0,0.0,1.0,1.0
1,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,...,1.0,1.0,1.0,1.0,5.0,0.0,1.0,1.0,1.0,1.0
2,1.0,1.0,1.0,2.0,1.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,5.0,0.0,0.0,1.0,1.0,1.0
3,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,...,1.0,0.0,1.0,1.0,5.0,0.0,0.0,1.0,1.0,0.0
4,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,2.0,...,1.0,1.0,1.0,1.0,5.0,1.0,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16795,2.0,2.0,0.0,2.0,0.0,5.0,1.0,2.0,1.0,2.0,...,0.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,0.0
16796,2.0,1.0,0.0,2.0,0.0,2.0,3.0,3.0,1.0,0.0,...,0.0,1.0,2.0,1.0,2.0,1.0,1.0,0.0,1.0,0.0
16797,2.0,2.0,2.0,2.0,0.0,2.0,0.0,2.0,1.0,0.0,...,2.0,2.0,2.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0
16798,2.0,2.0,2.0,2.0,0.0,3.0,0.0,2.0,0.0,0.0,...,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
16799,4.0,2.0,2.0,2.0,0.0,2.0,2.0,4.0,0.0,0.0,...,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0

In [ ]:
df_data1 = pd.concat([pd.DataFrame(df_data), pd.DataFrame(bin_labels)], axis = 0)
df_data1 = df_data1.transpose()
df_data1 = df_data1.reset_index(drop=True)

In [ ]:
df_data1